name: build-env
channels:
  # - defaults
  - conda-forge
dependencies:
  # Conda packages
  - python=3.11
  - pip
  - jupyter_server
  # - jupyterlite-core >=0.4.1,<0.5.0
  # - jupyterlite-xeus>=2.0.0,<3  # environment.yml
  # pip dependencies from requirements.txt
  - pip:
      # Use another requirements file.
      # Note that here also we can use relative paths.
      # pip will be run from the environment file directory, if provided.
      - -r requirements.txt