name: build-env
channels:
  # - defaults
  - conda-forge
dependencies:
  # Conda packages
  - python=3.11
  - pip
  - jupyter_server
  - jupyterlite-core >=0.4.1,<0.5.0
  # - jupyterlite-xeus>=2.0.0,<3
  - scipy
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  # pip dependencies from requirements.txt
  - pip:
      # - -r file:./requirements.txt
      - -r requirements.txt