name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  # - xeus-python
  - python=3.11
  - ipycanvas
  - scipy
  - numpy
  - pandas
  - matplotlib
  - scikit-learn